"use client";
import { Camera, Clock3, Cpu, Radio, Server, Wifi } from "lucide-react";
import { useTraffic } from "@/components/traffic-provider";
import { Badge, Card, SectionTitle } from "@/components/ui";

export default function HardwarePage() {
  const { state, connected } = useTraffic();
  if (!state) return <p>Loading hardware telemetry…</p>;
  return <>
    <SectionTitle title="Hardware Monitoring" description="Only registered ESP32 heartbeat and camera activity is shown—there are no simulated devices." action={<Badge className={connected ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}><Server size={12} /> API {connected ? "CONNECTED" : "OFFLINE"}</Badge>} />
    {!state.devices.length && <Card className="border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">No device is registered. Create one in Device setup, copy its API key into the ESP32 firmware, then send a heartbeat.</Card>}
    <div className="mt-5 grid gap-4 md:grid-cols-2">{state.devices.map((device) => <Card key={device.deviceId} className="p-5"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#e8f2ed] text-primary"><Cpu /></span><Badge className={device.online ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}><span className={device.online ? "h-2 w-2 rounded-full bg-emerald-500" : "h-2 w-2 rounded-full bg-red-500"} />{device.online ? "ONLINE" : "OFFLINE"}</Badge></div><h2 className="mt-4 font-bold text-[#173b2f]">{device.deviceId}</h2><p className="text-sm text-muted">{device.junctionName}</p><div className="mt-4 grid grid-cols-2 gap-3 text-xs">{[[Radio,"Last heartbeat",device.lastHeartbeat ? new Date(device.lastHeartbeat).toLocaleString() : "Never"],[Wifi,"WiFi",device.wifiSignal == null ? "No data" : `${device.wifiSignal} dBm`],[Camera,"Camera",device.cameraStatus],[Cpu,"Firmware",device.firmwareVersion]].map(([Icon,label,value]) => <div key={String(label)} className="rounded-xl border border-border p-3"><Icon size={16} className="text-primary" /><p className="mt-2 text-muted">{String(label)}</p><strong className="mt-1 block">{String(value)}</strong></div>)}</div></Card>)}</div>
    <Card className="mt-5 p-5"><div className="flex items-center gap-3"><Clock3 className="text-primary" /><div><h2 className="font-bold text-[#173b2f]">Signal data currently sent to ESP32</h2><p className="text-xs text-muted">Updated on each heartbeat and camera response.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(["lane1","lane2","lane3","lane4"] as const).map((lane, index) => { const active = state.currentLane === lane; const phase = active ? state.phase : "RED"; return <div key={lane} className={`rounded-xl border p-4 ${active ? "border-primary bg-emerald-50" : "border-border"}`}><div className="flex items-center justify-between"><strong>Lane {index + 1}</strong><span className={phase === "GREEN" ? "text-emerald-600" : phase === "YELLOW" ? "text-amber-600" : "text-red-600"}>{phase}</span></div><p className="mt-3 text-2xl font-black text-[#173b2f]">{active ? state.timer : "—"}<span className="ml-1 text-xs font-normal text-muted">{active ? "seconds left" : ""}</span></p><p className="mt-2 text-xs text-muted">{state.lanes[lane]} vehicles · next green {state.timings[lane]}s</p></div>; })}</div><p className="mt-4 text-xs text-muted">Operation: <strong className="text-[#173b2f]">{state.operation.status}</strong> · Camera interval: <strong className="text-[#173b2f]">{state.settings.cameraIntervalSeconds}s</strong></p></Card>
    {state.lastDetection && <Card className="mt-5 p-5"><h2 className="font-bold text-[#173b2f]">Most recent camera frame</h2><div className="mt-4 grid gap-4 md:grid-cols-[320px_1fr]"><img src={state.lastDetection.annotatedImage} alt="Vehicle detector output" className="w-full rounded-xl border border-border" /><div className="text-sm"><p><strong>{state.lastDetection.vehicleCount}</strong> vehicles detected</p><p className="mt-2 text-muted">Lane {state.lastDetection.lane.slice(-1)} · source {state.lastDetection.source}</p><p className="mt-2 text-muted">{new Date(state.lastDetection.capturedAt).toLocaleString()} · {state.lastDetection.inferenceMs} ms</p></div></div></Card>}
  </>;
}
