import { AlertTriangle, Camera, Cable, CircuitBoard, CloudUpload, Cpu, Network, Power, ShieldCheck, Timer } from "lucide-react";
import { Badge, Card, SectionTitle } from "@/components/ui";

const cameraPins = [
  ["3.3V", "3.3V", "Camera power; never use 5V"],
  ["GND", "GND", "Common logic ground"],
  ["SIOC / SCL", "GPIO 27", "Camera configuration clock"],
  ["SIOD / SDA", "GPIO 26", "Camera configuration data"],
  ["XCLK", "GPIO 21", "8 MHz clock generated by ESP32 LEDC timer 0"],
  ["PCLK", "GPIO 22", "Pixel clock input"],
  ["VSYNC", "GPIO 25", "Frame synchronization"],
  ["HREF", "GPIO 23", "Line synchronization"],
  ["D0", "GPIO 4", "Pixel data bit 0"],
  ["D1", "GPIO 5", "Pixel data bit 1"],
  ["D2", "GPIO 18", "Pixel data bit 2"],
  ["D3", "GPIO 19", "Pixel data bit 3"],
  ["D4", "GPIO 36", "Pixel data bit 4; input only"],
  ["D5", "GPIO 39", "Pixel data bit 5; input only"],
  ["D6", "GPIO 34", "Pixel data bit 6; input only"],
  ["D7", "GPIO 35", "Pixel data bit 7; input only"],
  ["RESET", "3.3V", "Held high; firmware uses -1"],
  ["PWDN", "GND", "Held low; firmware uses -1"],
];

const lampPins = [
  ["Lane 1", "MCP GPA0", "MCP GPA1", "MCP GPA2"],
  ["Lane 2", "MCP GPA3", "MCP GPA4", "MCP GPA5"],
  ["Lane 3", "MCP GPA6", "MCP GPA7", "MCP GPB0"],
  ["Lane 4", "MCP GPB1", "MCP GPB2", "MCP GPB3"],
];

const steps = [
  [CircuitBoard, "1. Register the ESP32", "Open Device setup, enter a unique Device ID and junction name, then copy the generated API key."],
  [Camera, "2. Connect the OV7670", "Use the exact table below. Keep D0-D7 and clock wires short; add a 100 nF capacitor near the camera."],
  [Cable, "3. Connect the MCP23017", "Connect VCC to 3.3V, GND to GND, SDA to GPIO 26, SCL to GPIO 27, and A0/A1/A2 to GND for address 0x20."],
  [Power, "4. Connect lamp drivers", "Each MCP output goes to an opto-isolated MOSFET/relay input. Lamp power comes from the separate 12V supply."],
  [Network, "5. Configure Wi-Fi and API", "Put the 2.4 GHz Wi-Fi name, password, Render API URL, Device ID, API key, and lane in the firmware."],
  [CloudUpload, "6. Flash and test", "Confirm heartbeat first, then camera upload, then test each lamp with low-voltage LEDs before connecting signal heads."],
];

export default function InstallationPage() {
  return <>
    <SectionTitle title="ESP32 Hardware Installation" description="Exact reference wiring for the included ESP32 + OV7670 + MCP23017 firmware." action={<Badge className="border-emerald-200 bg-emerald-50 text-emerald-700">FIRMWARE PIN MAP</Badge>} />

    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      {steps.map(([Icon, title, text]) => <Card key={String(title)} className="p-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#e8f2ed] text-primary"><Icon size={21} /></span><h2 className="mt-4 font-bold text-[#173b2f]">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-muted">{String(text)}</p></Card>)}
    </div>

    <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card className="overflow-hidden">
        <div className="border-b border-border p-5"><div className="flex items-center gap-3"><Camera className="text-primary" /><div><h2 className="font-bold text-[#173b2f]">OV7670 to ESP32 wiring</h2><p className="text-xs text-muted">This matches the constants in the included Arduino firmware.</p></div></div></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[570px] text-left text-sm"><thead className="bg-[#f4f7f5] text-xs text-muted"><tr><th className="px-5 py-3">OV7670 pin</th><th className="px-5 py-3">ESP32 connection</th><th className="px-5 py-3">Purpose</th></tr></thead><tbody>{cameraPins.map((row) => <tr key={row[0]} className="border-t border-border"><td className="px-5 py-3 font-semibold text-[#173b2f]">{row[0]}</td><td className="px-5 py-3 font-mono text-xs text-primary">{row[1]}</td><td className="px-5 py-3 text-xs text-muted">{row[2]}</td></tr>)}</tbody></table></div>
      </Card>

      <div className="space-y-5">
        <Card className="p-5"><div className="flex items-center gap-3"><CircuitBoard className="text-primary" /><div><h2 className="font-bold text-[#173b2f]">MCP23017 connection</h2><p className="text-xs text-muted">The camera uses most ESP32 pins, so lamps use an I/O expander.</p></div></div><div className="mt-4 space-y-2 text-sm">{[
          ["MCP VDD", "ESP32 3.3V"], ["MCP VSS", "ESP32 GND"], ["MCP SDA", "ESP32 GPIO 26"],
          ["MCP SCL", "ESP32 GPIO 27"], ["MCP A0, A1, A2", "GND (I2C address 0x20)"],
          ["MCP RESET", "3.3V through 10 kΩ"], ["100 nF capacitor", "Between MCP VDD and GND"],
        ].map(([left, right]) => <div key={left} className="flex justify-between gap-3 rounded-xl border border-border px-3 py-2"><span className="font-semibold text-[#173b2f]">{left}</span><span className="text-right text-muted">{right}</span></div>)}</div></Card>

        <Card className="border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-amber-700" /><div><h2 className="font-bold text-amber-900">Do not connect lamps directly</h2><p className="mt-2 text-sm leading-6 text-amber-800">MCP23017 outputs are logic signals only. Every output must drive an opto-isolated MOSFET or relay module. The 12V lamp supply must have its own fuse and protection.</p></div></div></Card>
      </div>
    </div>

    <Card className="mt-5 overflow-hidden">
      <div className="border-b border-border p-5"><div className="flex items-center gap-3"><Cable className="text-primary" /><div><h2 className="font-bold text-[#173b2f]">Traffic lamp output map</h2><p className="text-xs text-muted">MCP23017 pin → opto-isolated driver input → 12V traffic lamp.</p></div></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-[#f4f7f5] text-xs text-muted"><tr><th className="px-5 py-3">Approach</th><th className="px-5 py-3 text-red-600">Red driver</th><th className="px-5 py-3 text-amber-600">Yellow driver</th><th className="px-5 py-3 text-emerald-600">Green driver</th></tr></thead><tbody>{lampPins.map((row) => <tr key={row[0]} className="border-t border-border">{row.map((cell, index) => <td key={cell} className={`px-5 py-4 ${index === 0 ? "font-bold text-[#173b2f]" : "font-mono text-xs"}`}>{cell}</td>)}</tr>)}</tbody></table></div>
    </Card>

    <div className="mt-5 grid gap-5 lg:grid-cols-3">
      <Card className="p-5"><Timer className="text-primary" /><h2 className="mt-3 font-bold text-[#173b2f]">Which timer is used?</h2><p className="mt-2 text-sm leading-6 text-muted">Traffic red/green/yellow countdowns run on the backend and are returned to ESP32 every heartbeat. No external timer IC is required. ESP32 LEDC timer 0 is used only to generate the OV7670 XCLK.</p></Card>
      <Card className="p-5"><Cpu className="text-primary" /><h2 className="mt-3 font-bold text-[#173b2f]">Firmware libraries</h2><p className="mt-2 text-sm leading-6 text-muted">Install ArduinoJson, Adafruit MCP23X17, and Espressif esp32-camera. Select an ESP32 board with PSRAM when available.</p></Card>
      <Card className="p-5"><ShieldCheck className="text-primary" /><h2 className="mt-3 font-bold text-[#173b2f]">Safe startup behavior</h2><p className="mt-2 text-sm leading-6 text-muted">Keep all approaches red until Wi-Fi, heartbeat authentication, and a running traffic session are confirmed. Test with small LEDs before connecting real lamps.</p></Card>
    </div>

    <Card className="mt-5 p-5"><h2 className="font-bold text-[#173b2f]">Real-time data exchanged with ESP32</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-[#102b22] p-4 font-mono text-xs leading-6 text-emerald-50"><span className="text-emerald-300">ESP32 → server</span><br />deviceId, Wi-Fi RSSI, firmware version, camera status<br />JPEG image + lane number</div><div className="rounded-xl bg-[#102b22] p-4 font-mono text-xs leading-6 text-emerald-50"><span className="text-emerald-300">Server → ESP32</span><br />operation status, active lane, phase, remaining seconds<br />all lane red/yellow/green states, calculated green times<br />next camera capture interval</div></div></Card>
  </>;
}
